add_newline = false



#format = "\[custom thingy\]"
format = '\[$time$username$directory$git_status\] '


[username]
show_always = false
style_user = "white"
format = "[$user]($style) "

[time]
disabled = false
use_12hr = true
style = "white"
format = "[$time]($style) "
time_format = "%-l:%M%P"

[directory]
style = "#d36eff"
truncate_to_repo = false
truncation_length = -1

[character]                            # The name of the module we are configuring is "character"
success_symbol = ""     # The "success_symbol" segment is being set to "➜" with the color "bold green"


[package]
disabled = true
